name: StatusMessages
version: 1.1.2
author: qwhaty & Smayd35
main: me.qwhaty.status.Main
description: Adds a variety a commands to change your in-game status

depend: [PlaceholderAPI]

commands:
  donotdisturb:
    aliases: [dnd]
    usage: /donotdisturb
    description: Changes the player's status to "Do Not Disturb"
  streaming:
    aliases: [str]
    usage: /streaming
    description: Changes the player's status to "Streaming"
  building:
    aliases: []
    usage: /building
    description: Changes the player's status to "Building"
  recording:
    aliases: [rec]
    usage: /recording
    description: Changes the player's status to "Recording"